import pandas as pd
import os

def export_for_tradingview():
    input_file = "daily_candidates.csv"
    output_file = "tradingview_watchlist.txt"

    if not os.path.exists(input_file):
        print(f"❌ Error: {input_file} not found. Run a scan first.")
        return

    # Read the candidates generated by run_scan.py
    df = pd.read_csv(input_file)
    
    if 'Ticker' not in df.columns:
        print("❌ Error: 'Ticker' column missing.")
        return

    # Extract tickers and save to a plain text file
    tickers = df['Ticker'].tolist()
    
    with open(output_file, 'w') as f:
        # TradingView accepts a simple comma-separated or new-line list
        f.write(",".join(tickers))
    
    print(f"✅ Exported {len(tickers)} tickers to {output_file}")
    print("👉 Download this file to your Mac to import into TradingView.")

if __name__ == "__main__":
    export_for_tradingview()